spring:
  application:
    name: mozprops-api
  
  datasource:
    url: jdbc:postgresql://localhost:5432/mozprops
    username: mozprops
    password: mozprops
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false
    validate-on-migrate: true
    locations: classpath:/db/migration
    # user: mozprops
    # password: mozprops
    # url: jdbc:postgresql://localhost:5432/mozprops

local:
  storage:
    location: /Users/macpro2017/mozprops/storage

aws:
  s3:
    bucket:
      name: mozprops-images
    region: us-east-1
    access-key: AKIAIOSFODNN7EXAMPLE
    secret-key: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY


